# Base image
FROM runpod/base:0.4.0-cuda11.8.0

RUN apt-get update && apt-get install -y ffmpeg \
    build-essential \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
COPY builder/requirements.txt /requirements.txt
RUN python3.11 -m pip install --upgrade pip && \
    python3.11 -m pip install --upgrade -r /requirements.txt --no-cache-dir && \
    rm /requirements.txt

COPY builder/preload.py /preload.py
RUN python3.11 /preload.py && \
    rm /preload.py

# Add src files (Worker Template)
ADD src /src

WORKDIR /src

RUN pip install .

CMD ["python3.11", "-u", "handler.py"]
